#!/bin/sh

#===============================================================================
# DESCRIPTION
#
# This script builds a LaTeX file using `latexmk'.
#===============================================================================

# Build the document
latexmk -f -interaction=nonstopmode \
           -pdf -pdflatex="pdflatex --shell-escape %O %S" \
           -bibtex ${1}.tex

# Rename the document to TARGET
mv ${1}.pdf ${2}
